server:
  port: 8012

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: minitor-stream
          group: group1
          consumer:
            durableSubscription: true
  rabbitmq:
    username: user
    password: password
    addresses: 172.18.216.86:5673


