server:
  port: 8012

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: minitor-stream
          group: group1
          consumer:
            durableSubscription: true
  rabbitmq:
    username: user
    password: password
    addresses: 172.18.216.86:5673

  datasource:
#    url: jdbc:mysql://172.18.216.86:10004/minitor?characterEncoding=utf8&useSSL=false
    url: jdbc:mysql://192.168.0.87:3306/minitor?autoReconnect=true&useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      max-idle: 10
      max-wait-millis: 10000
      min-idle: 5
      initial-size: 5
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update



