server:
  port: 8011

spring:
  cloud:
    stream:
      bindings:
        output:
          destination: minitor-stream
  rabbitmq:
    username: user
    password: password
#    host: 172.18.218.252
#    port: 15673
    addresses: 172.18.216.86:5673
