server:
  port: 8011

spring:
  cloud:
    stream:
      bindings:
        output:
          destination: ${STREAM_NAME:overview-stream}
  rabbitmq:
    username: ${RABBIT_NAME:user}
    password: ${RABBIT_PASS:password}
    addresses: ${RABBIT_ADDRESS}
#  rabbitmq:
#    username: user
#    password: password
#    addresses: 172.18.216.86:5673
