server:
  port: 8011

spring:
  cloud:
    stream:
      bindings:
        output:
          destination: minitor-stream
  rabbitmq:
    username: user
    password: password
    addresses: 172.18.216.86:5673
