server:
  port: 8012

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: overview-stream
          group: group1
          consumer:
            durableSubscription: true
  rabbitmq:
    username: user
    password: passworrd
    addresses: 192.168.0.100:5672
#    username: ${RABBIT_NAME}
#    password: ${RABBIT_PASS}
#    addresses: ${RABBIT_ADDRESS}

  datasource:
    url: jdbc:mysql://192.168.0.100/monitor?autoReconnect=true&useSSL=false
    username: root
    password: root
#    url: ${MYSQL_URL}
#    username: ${MYSQL_NAME}
#    password: ${MYSQL_PASS}
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      max-idle: 10
      max-wait-millis: 10000
      min-idle: 5
      initial-size: 5
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update



