server:
  port: 8012

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: ${STREAM_NAME:overview-stream}
          group: group1
          consumer:
            durableSubscription: true
  rabbitmq:
#    username: user
#    password: passworrd
#    addresses: 192.168.0.100:5672
    username: ${RABBIT_NAME:user}
    password: ${RABBIT_PASS:password}
    addresses: ${RABBIT_ADDRESS:192.168.0.102:5672}

  datasource:
#    url: jdbc:mysql://192.168.0.100/monitor?autoReconnect=true&useSSL=false
#    username: root
#    password: root
    url: jdbc:mysql://${MYSQL_ADDRESS:192.168.0.100:3306}/monitor?autoReconnect=true&useSSL=false
    username: ${MYSQL_NAME:root}
    password: ${MYSQL_PASS:root}
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      max-idle: 10
      max-wait-millis: 10000
      min-idle: 5
      initial-size: 5
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update



