server:
  port: 10011
  tomcat:
    max-threads: ${MAX_THREADS:10}
    accept-count: ${ACCEPT_COUNT:10}
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    hostname: ${EUREKA_ADDRESS:192.168.0.100}
    port:  ${EUREKA_PORT:8001}
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

service:
  method1: ${METHOD1:80}
  method2: ${METHOD2:10}
  times1: ${TIMES1:16}