server:
  port: 10011
  tomcat:
    max-threads: ${MAX_THREADS:10}
    accept-count: ${ACCEPT_COUNT:10}
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    hostname: ${EUREKA_ADDRESS:192.168.0.100}
    port:  ${EUREKA_PORT:8001}
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
spring:
  cloud:
    stream:
      bindings:
        output_channel_service:
          destination: overview-service
          content-type: application/json
  rabbitmq:
    username: ${RABBIT_NAME:user}
    password: ${RABBIT_PASS:password}
    addresses: ${RABBIT_ADDRESS:192.168.0.101:5672}

service:
  method1: ${METHOD1:80}
  method2: ${METHOD2:10}
  times1: ${TIMES1:16}