server:
  port: 10012

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    hostname: ${EUREKA_ADDRESS:192.168.0.100}
#    port:  ${EUREKA_PORT:8093}
    port:  ${EUREKA_PORT:8001}
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/