server:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://192.168.0.100/monitor?autoReconnect=true&useSSL=false
    username: root
    password: root
#    url: ${MYSQL_URL}
#    username: ${MYSQL_NAME}
#    password: ${MYSQL_PASS}
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      max-idle: 10
      max-wait-millis: 10000
      min-idle: 5
      initial-size: 5
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update

rancher:
  host: 192.168.0.100
  port: 8080
  APIkey:
    accesskey: 17D2E910090C61661B83
    secret: rXqsHJA5i425oiFqqJ7Ebm1zB9DSmSXXh4zoT1hH
  stackapisurl: v2-beta/projects/1a5/stacks/1st10

  webhooks:
    syslog:
      up: http://172.18.218.252:8080/v1-webhooks/endpoint?key=zTAUvX07UY4PbmEZ3MHcGHGDLo4N1TRuDUxrFnww&projectId=1a5
      down: http://172.18.218.252:8080/v1-webhooks/endpoint?key=zTAUvX07UY4PbmEZ3MHcGHGDLo4N1TRuDUxrFnww&projectId=1a5
    syslog2:
      up: syslog2up
      down: syslog2down

