server:
  port: 8003

spring:
  application:
    name: rancherAdapter

prometheus:
  address: 192.168.0.100:9090

rancher:
  host: 192.168.0.100
  port: 8080
  APIkey:
    accesskey: 600846BEC82913C1DD1D
    secret: 5VrwxXgNsWMR1Dz4i2TuvCv7VGGB6n54C5NHrhz2
  stackapisurl: v2-beta/projects/1a5/stacks/1st5
  webhooks:
    syslog:
      up: http://172.18.218.252:8080/v1-webhooks/endpoint?key=zTAUvX07UY4PbmEZ3MHcGHGDLo4N1TRuDUxrFnww&projectId=1a5
      down: http://172.18.218.252:8080/v1-webhooks/endpoint?key=zTAUvX07UY4PbmEZ3MHcGHGDLo4N1TRuDUxrFnww&projectId=1a5
    syslog2:
      up: syslog2up
      down: syslog2down