server:
  port: 8003

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    hostname: ${EUREKA_ADDRESS:192.168.0.100}
#    port:  ${EUREKA_PORT:8093}
    port:  ${EUREKA_PORT:8001}
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/


prometheus:
  address:  ${PROMETHEUS_ADDRESS:192.168.0.100:9090}

rancher:
  host: ${RANCHER_HOST:192.168.0.100}
  port: ${RANCHER_PORT:8080}
  APIkey:
    accesskey: ${RANCHER_API_KEY:600846BEC82913C1DD1D}
    secret: ${RANCHER_API_SECRET:5VrwxXgNsWMR1Dz4i2TuvCv7VGGB6n54C5NHrhz2}
  stackApiUrl: ${RANCHER_STACK_URL:v2-beta/projects/1a5/stacks/1st9}
  webHooks:
    ServiceA:
      up: http://192.168.0.100:8080/v1-webhooks/endpoint?key=GmLpObgPiCHd70s9TOvKgTanb14EXabsdehTvT7o&projectId=1a5
      down: http://192.168.0.100:8080/v1-webhooks/endpoint?key=boNc3L9clBB4E8YKxaGTeHLsDwlRgI8v5YWPDEwP&projectId=1a5
    ServiceB:
      up: http://192.168.0.100:8080/v1-webhooks/endpoint?key=lYkupO7mFZ4dDFL6DFl45ybSaNpFhf8i9F12Vmzn&projectId=1a5
      down: http://192.168.0.100:8080/v1-webhooks/endpoint?key=bLCtJ7Q9uiPPx4F4wGmoJikYbYP3BV2HzWXizQ9O&projectId=1a5
    ServiceC:
      up: http://192.168.0.100:8080/v1-webhooks/endpoint?key=k2A7pUml0kLFVdaJMekqGWIJijESjsMYPMF21Pun&projectId=1a5
      down: http://192.168.0.100:8080/v1-webhooks/endpoint?key=61am4fV4xWSGbvc8ykY1IOXETktGMkixwcvU4eRC&projectId=1a5
    ServiceD:
      up: http://192.168.0.100:8080/v1-webhooks/endpoint?key=lqxR42wW3SVRHXMqQ4Ss44VvOYP94OdqXdm3MzKa&projectId=1a5
      down: http://192.168.0.100:8080/v1-webhooks/endpoint?key=sZ4vBqdTkJAcySusonUhXUpZB5mm81THaOpmXrU4&projectId=1a5